services:

  auth:
    container_name: keycloak0
    image: quay.io/keycloak/keycloak:26.0.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8081:8080
