spring:
    application:
        name: keycloak-intro
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/realms/realmtest
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
