services:

  db:
    container_name: mysql1
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
      container_name: adminer1
      image: adminer
      ports:
        - 8081:8080